name: Azure DNS Zone Updater
version: "1"
slug: azure_dns_zone_updater
description: Azure DNS Zone updater add-on for Home Assistant
url: https://github.com/JanneMattila/hassio-addon-azuredns
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options:
  seconds: 3600
  aad_tenant_dd: "<your_tenant_id>"
  aad_client_id: "<your_app_id>"
  aad_client_secret: "<your_app_secret>"
  dns_zone_id: "/subscriptions/<your_sub_id>/resourceGroups/<your_rg>/providers/Microsoft.Network/dnszones/<your_dns_zone>"
  record_type: "A"
  record_name: "demo1"
schema:
  seconds: int
  aad_tenant_dd: str
  aad_client_id: str
  aad_client_secret: password
  dns_zone_id: str
  record_type: str
  record_name: str
image: jannemattila/azure-dns-zone-updater-{arch}
